GET http://localhost:8080/groups/users
Content-Type: application/json

{
    "groupID" : 2
}


###

POST http://localhost:8080/groups/adduser
Content-Type: application/json

{
    "userID" : 1,
    "inviteCode" : "XYGRB"
}
